development:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.config.settings.app_name %>_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.config.settings.app_name %>_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.config.settings.app_name %>_production
  pool: 5
