development:
  adapter: postgresql
  encoding: unicode
  database: verdeforum_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: verdeforum_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: verdeforum_production
  pool: 5
